version: "3.8"

services:
  db:
    container_name: todolist-spring-boot
    image: postgres:latest
    environment:
      POSTGRES_USER: Rediet
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5333:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
